<?php exit;?>2014-03-27 17:08:22<br />
<div align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 信息在网站上的排名对于很多会员来说都是很重要的。因为，自己所发布的信息排在越前，就越容易让客户获悉；而且有一部分客户甚至会认为位置排在越前的商家/产品，质量会越好。因此，很多会员都希望自己的信息可以排在前面。那么，天成网上的信息排列有什么奥秘，可以参考以下10条小建议。</div>
<div align="left"><span><span>&nbsp; </span></span><b>信息推荐到首页规则</b>：</div>
<div align="left"><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><b>1. </b><b>合法真实</b>：发布的信息内容必须合法真实有效，而不是虚构的，且须与医疗器械相关。举例说明，有会员在供应信息处发布不真实的求购信息，刚好有商户看到，进而联系您，您却说这个是您随便发送的，商家投诉到网站客服这边，那么一经客服核实情况无误后，可能会屏蔽掉您的会员账号；又如您发布的信息涉及违反国家法律法规，那么此信息将会被删除，而您的会员账号也会被监控甚至屏蔽。</div>
<div align="left"><span><span>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><b>2.</b><b>字段清晰：</b>信息内容的措辞清晰有条理，那么系统可以很好的识别，这对信息排放的位置也会有影响<b>。</b>如果所发布的信息内容是非常不清晰，系统很可能会拒绝此信息的发放。</div>
<div align="left"><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><b>3.</b><b>内容详细：</b>如果您上传的信息内容越详细，那么显示的位置也会越前。例如，您上传一条技术服务需求信息，内容越详细，那么系统刷新排列的位置就会越前<b>。</b></div>
<div align="left"><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><b>4.</b><b>有图有真相：</b>有图片的信息排列往往要比没有图片的信息排列的位置要前。就好像发布一条服务供应商的简历，有头像的简历所排列的位置都会比没有头像的位置前；还有上传的产品信息，有图文解说、信息详细的，系统都会将这类信息的位置刷前<b>。</b></div>
<div align="left"><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><b>5.</b><b>独有不重复：</b>发布的信息内容最好不要与之前发布的信息重复。如果您发布的产品信息都是重复的，那么，客户搜索贵公司的产品时，就会出现一系列重复的产品信息，这样一来，客户对贵公司的专业性及产品的多样性就会有怀疑。</div>
<div align="left"><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><b>6. </b><b>新近<span>/精彩吸引人：</span></b>发布的信息内容可新近、独特、吸人眼球。如，您发布的&ldquo;医疗咨询&rdquo;新颖独特，又有时效性，那么通过天成网客服认证的可能性就会越高，而且，对客户的吸引性也会越高，点击率自然就高。</div>
<div align="left"><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><b>7.</b><b>点击次数：</b>信息浏览次数的多少，对排列的位置也会有所影响。浏览次数越多，证明该信息对客户的吸引度越高，因此，系统会将这类点击率高的信息往前排列。</div>
<div align="left"><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><b>8. </b><b>收费<span>/竞投：</span></b>天成网页上有些广告位是通过收费<span>/竞投来使用的，位置越前、越显眼，收费的标准都会有所不同。</span></div>
<div align="left"><span>&middot;<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><b>9. VIP</b><b>会员：</b>会员的级别不同，也会影响信息排列的位置，如果您是<span>VIP会员，那么您发布的信息就会比普通会员或是开店会员发布的信息所在的位置之前</span></div>
<div align="left"><span>&middot;<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><b>10. </b><b>通过客服认证：</b>即信息是通过天成网客服的审核认可推荐，允许放在天成网上宣传的。只要符合上面的第一到第七条，一般都可以通过客服认证。（此认证是天成医疗网所认可的）</div>