<?php exit;?>2014-10-30 10:50:29<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px">&nbsp;<span style="line-height: 27px">模拟器产品详细描述如下</span></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px"><span style="line-height: 27px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;胎心探头检测仪的LED显示管，当5秒内没有操作按键时，将自动关闭显示，以便节电。按任意按键则触发再次显示。</span></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px">按键说明<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一共有四个按键，依次为选择键、增加键、减小键、确认键，另外还有一组组合键<br />
选择键：<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此按键用来选择要改变的参数，共有4个LED管来显示4个代码，分别代表显示的内容，<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 第2-4位代表要更改的参数（2是数值的百位，3代表十位，4代表个位）<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; LED管右下脚的亮点，表示现在选择的内容；可以进行更改。<br />
增加键：<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当使用选择键选择好更改内容后，使用此键进行参数更改。<br />
减小键：<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当使用选择键选择好更改内容后，使用此键进行参数更改。<br />
确认键：<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当参数更改完毕后，此键确认后将确认参数的更改，并产生相应的波形。<br />
组合键：<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 按下选择键的同时，再按下确认键，松开确认键，松开选择键，这时表示选择了一次组合键，再次按下确认键后将显示不同的内容。</span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px"><u><span style="font-family: kaiti_gb2312">&nbsp;&nbsp;模拟仪上电后工作于120bpm，此时连接到外置工装后，将探头放置于工装下方。胎心率探头就可以检测出胎心率数值。</span></u></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px">&nbsp;</span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px"><strong><span style="line-height: 1.5">&nbsp; 胎心率频率设置范围：</span></strong></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 30-240&nbsp;&nbsp; bpm</strong></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px"><strong>&nbsp;&nbsp;&nbsp;&nbsp; 调整步长：</strong></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1bpm</strong></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px"><strong>&nbsp;&nbsp;&nbsp;&nbsp; 误差：</strong></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &plusmn;1 bpm</strong></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<u><strong>强度可调整</strong></u></span></span></p>
<p style="padding-bottom: 0px; line-height: 21px; text-indent: 0px; margin: 1.12em 0px; padding-left: 0px; padding-right: 0px; font-family: tahoma, arial, 宋体, sans-serif; color: rgb(64,64,64); padding-top: 0px"><span style="color: #000000"><span style="font-size: 14px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span></p>