<?php exit;?>2014-10-31 16:51:02&nbsp; &nbsp; &nbsp;&nbsp;<span style="line-height: 28px; text-indent: 2em; letter-spacing: 0px; font-family: 宋体; color: rgb(115,115,115)">北京市的第二类<strong>体外诊断试剂注册</strong>需要提交的资料，来源于《</span><span style="font-family: 宋体">北京市第二类体外诊断试剂产品首次注册</span><span style="line-height: 28px; text-indent: 2em; letter-spacing: 0px; font-family: 宋体; color: rgb(115,115,115)">》的法规要求：</span>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">所需资料如下：</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">1．&nbsp;申请表</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">1</span>）应有法定代表人或负责人签字并加盖公章；</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">2</span>）&ldquo;申请人（企业名称）&rdquo;、&ldquo;申请人住所&rdquo;与工商营业执照中相应内容一致；</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">3</span>）&ldquo;产品名称&rdquo;、&ldquo;包装规格&rdquo;与所提交的已预评价的产品技术要求、检测报告等申报资料中相应内容一致。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">2．证明性文件</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">1</span>）企业营业执照副本复印件，且应在有效期内；</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">2</span>）组织机构代码证复印件，且应在有效期内；</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">3</span>）按照创新医疗器械特别审批程序审批的境内第二类体外诊断试剂产品申请注册时，样<span style="font-family: 'Times New Roman'">3</span>．综述资料</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">1</span>）产品的预期用途</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">2</span>）产品描述</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">3</span>）有关生物安全性方面的说明</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">4</span>）有关产品主要研究结果的总结和评价。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">5</span>）其他</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">4．分析性能评估资料</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">1</span>）体外诊断试剂的分析性能评估主要包括精密度、准确度、灵敏度、特异性、线性范围或测定范围等项目。应当对多批产品进行性能评估，对结果进行统计分析，以有效地控制产品生产工艺及产品质量的稳定。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">2</span>）校准品应当提交完整的溯源性文件。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">3</span>）质控品应当提交在所有适用机型上进行的定值资料。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">5．阳性判断值或参考区间确定资料</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">6．稳定性研究资料</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">7．生产及自检记录</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">提供连续三批产品生产及自检记录的复印件。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">8．临床评价资料</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">包括相应的临床试验资料和<span style="font-family: 'Times New Roman'">/</span>或非临床评价资料。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">1</span>）临床试验</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">需要进行临床试验的体外诊断试剂，申请人应当参考有关技术指导原则开展临床试验，并提供以下临床试验资料：</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">a.伦理委员会同意临床试验开展的书面意见。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">b.临床试验方案</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">c.各临床试验机构的临床试验报告</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">d.对所有临床试验结果的总结报告</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">e.临床试验报告附件</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">(2)国家食品药品监督管理总局发布的免于进行临床试验的体外诊断试剂目录中的产品，应当提交相应的临床评价资料。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">3</span>）校准品、质控品不需要提供临床试验资料。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">4</span>）本部分所称临床试验机构盖章是指临床试验机构公章。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">9．产品风险分析资料</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">对体外诊断试剂产品寿命周期的各个环节<span style="font-family: 'Times New Roman'">,</span>从预期用途、可能的使用错误、与安全性有关的特征、已知和可预见的危害等方面的判定及对患者风险的估计进行风险分析、风险评价及相应的风险控制的基础上，形成风险管理报告。风险管理资料是对产品的风险管理过程及其评审的结果予以记录所形成的资料。风险管理资料应提供对于每项已判定危害的下列各个过程的可追溯性：</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">1</span>）对体外诊断试剂产品寿命周期的各个环节<span style="font-family: 'Times New Roman'">,</span>从预期用途、可能的使用错误、与安全性有关的特征、已知和可预见的危害等方面的判定及对患者风险的估计；</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">2</span>）风险评价：对每个已判定的危害处境，评价和决定是否需要降低风险；</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">3</span>）风险控制措施的实施和验证结果，必要时应引用检测和评价性报告；</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">4</span>）任何一个或多个剩余风险的可接受性评定；</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">5</span>）应符合相关行业标准的要求。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">10．产品技术要求</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">11．产品注册检验报告</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">12．产品说明书</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">13．标签样稿</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">14.&nbsp;符合性声明</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">符合性声明应由法定代表人或负责人签字并加盖企业公章，并包括以下内容：</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">1</span>）申请人声明本产品符合《体外诊断试剂管理办法》相关要求；声明本产品符合《体外诊断试剂管理办法》关于产品分类的原则及《体外诊断试剂分类子目录》有关分类的要求；声明本产品符合现行国家标准、行业标准，并提供符合标准的清单；</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">（<span style="font-family: 'Times New Roman'">2</span>）申请人所提交资料真实性的自我保证声明，并作出材料如有虚假承担法律责任的承诺。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">15．提交注册申请资料电子文档，至少应包括：</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">16．申报资料时，不是法定代表人或负责人本人的，应当提交《授权委托书》。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">17．提交申报资料目录。注册申报资料应有所提交资料的目录，包括申报资料的一级和二级标题。每项二级标题对应的资料应单独编制页码。</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px">以上为资料简要目录，具体要求详见：<span style="font-family: 宋体">《</span><span style="font-family: 宋体">北京市第二类体外诊断试剂产品首次注册</span><span style="font-family: 宋体">》</span></p>
<p style="padding-bottom: 0px; line-height: 28px; margin: 0px; padding-left: 0px; letter-spacing: 0px; padding-right: 0px; font-family: SimSun, 'Arial Narrow'; color: rgb(115,115,115); padding-top: 0px"><span style="font-family: 宋体">更多资讯请登录：弗锐达医疗器械咨询服务机构官网 http://www.fredamd.com<br />
<br />
<br type="_moz" />
</span></p>