<?php exit;?>2014-06-19 16:38:37<span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);">&nbsp;<span style="font-family: 宋体; text-indent: 2em;">主要特点</span> </span></span>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">实时弹性成像技术</span><span style="font-family: Verdana;">&lt;</span><span style="font-family: 宋体;">选配</span><span style="font-family: Verdana;">&gt;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">自适应声速优化</span><span style="font-family: Verdana;">&lt;</span><span style="font-family: 宋体;">选配</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">自适应组织结构强化</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">相位翻转谐波成像</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">系统升级功能</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">自适应斑点杂讯抑制算法</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">方向性多普勒血流能量图</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">远程系统维修及技术支持</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">3-D&nbsp;和</span><span style="font-family: Verdana;">4-D&nbsp;</span><span style="font-family: 宋体;">超声及图像编辑</span><span style="font-family: Verdana;">&lt;</span><span style="font-family: 宋体;">选配&gt;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">支持多种数据存储及参数优化</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">图像模式&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">&nbsp;B</span><span style="font-family: 宋体;">，</span><span style="font-family: Verdana;">2B,4B,B</span><span style="font-family: 宋体;">／</span><span style="font-family: Verdana;">M&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">&nbsp;CFM</span><span style="font-family: 宋体;">，</span><span style="font-family: Verdana;">B</span><span style="font-family: 宋体;">／</span><span style="font-family: Verdana;">BC,</span><span style="font-family: 宋体;">&nbsp;</span><span style="font-family: Verdana;">ColorM&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">PW</span><span style="font-family: 宋体;">模式，</span><span style="font-family: Verdana;">HPRF,CW</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">能量多普勒／方向能量多普勒&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">二维成像&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">梯形成像，宽景成像&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">自由臂三维成像&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">实时三同步成像</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">图象优化</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">OPT&nbsp;</span><span style="font-family: 宋体;">一键优化功能，实时、非预设置二维、频谱多普勒模式一键式自动图像优化。</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">DICOM&nbsp;</span><span style="font-family: 宋体;">标准支持影像交互和管理；</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">可变频带的图像类型选择；</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">强化彩色血流分辨率技术；</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">像素优化、斑点噪音消除技术；</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">实时双帧斑点噪音消除前后显示技术；</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">自适应扫描控制技术；</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">4平滑处理，</span><span style="font-family: Verdana;">4</span><span style="font-family: 宋体;">级边缘增强；</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">自动组织（图像）显示优化技术</span><span style="font-family: Verdana;">&lt;</span><span style="font-family: 宋体;">选配</span><span style="font-family: Verdana;">&gt;</span><span style="font-family: 宋体;">；</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Verdana;">测量软件包</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">产科测量</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">妇科测量</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">泌尿系统测量</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">小器官测量</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">放射科测量</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">心脏测量</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">在频谱多普勒计算中进行</span><span style="font-family: Verdana;">E</span><span style="font-family: 宋体;">、</span><span style="font-family: Verdana;">A</span><span style="font-family: 宋体;">和</span><span style="font-family: Verdana;">Vmax</span><span style="font-family: 宋体;">测量</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">在</span><span style="font-family: Verdana;">PW</span><span style="font-family: 宋体;">和</span><span style="font-family: Verdana;">CW</span><span style="font-family: 宋体;">中进行速度时间积分</span><span style="font-family: Verdana;">VTI</span><span style="font-family: 宋体;">、压力减半时间（</span><span style="font-family: Verdana;">PHT</span><span style="font-family: 宋体;">）</span><span style="font-family: Verdana;">dP:dT</span><span style="font-family: 宋体;">、主动脉瓣面积</span><span style="font-family: Verdana;">AVA</span><span style="font-family: 宋体;">、每搏输出量</span><span style="font-family: Verdana;">SV</span><span style="font-family: 宋体;">、心输出量</span><span style="font-family: Verdana;">CO</span><span style="font-family: 宋体;">、心率的计算。</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">标准配置</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">标准配置：主机、</span><span style="font-family: Verdana;">17</span><span style="font-family: 宋体;">英寸液晶显示器</span><span style="font-family: Verdana;">,&nbsp;3</span><span style="font-family: 宋体;">．</span><span style="font-family: Verdana;">5MHz</span><span style="font-family: 宋体;">腹部凸阵探头，&nbsp;</span><span style="font-family: Verdana;">1</span><span style="font-family: 宋体;">7</span><span style="font-family: Verdana;">英寸液晶显示器，<font face="Verdana">3</font></span><span style="font-family: 宋体;">个探头插座，</span><span style="font-family: Verdana;">160G</span><span style="font-family: 宋体;">硬盘，</span><span style="font-family: Verdana;">DVD</span><span style="font-family: 宋体;">刻录，</span><span style="font-family: Verdana;">2</span><span style="font-family: 宋体;">个</span><span style="font-family: Verdana;">USB</span><span style="font-family: 宋体;">接口</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: Tahoma;">&nbsp;</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>
<p class="p0" style="margin-bottom: 0pt; margin-top: 0pt; background-position: initial initial; background-repeat: initial initial;"><span style="font-size: 14px;"><span style="color: rgb(0, 0, 0);"><span style="font-family: 宋体;">用户接口：包括：</span><span style="font-family: Verdana;">USB</span><span style="font-family: 宋体;">、</span><span style="font-family: Verdana;">DIOCOM</span><span style="font-family: 宋体;">、</span><span style="font-family: Verdana;">S-VIDEO</span><span style="font-family: 宋体;">等端口，音源输出、</span><span style="font-family: Verdana;">VGA</span><span style="font-family: 宋体;">接口，串口、欲留将来升级的外接</span><span style="font-family: Verdana;">&nbsp;ECG&nbsp;</span><span style="font-family: 宋体;">接口。</span></span></span><span style="color: rgb(51, 51, 51); font-size: 8.5pt; font-family: Tahoma; background-position: initial initial; background-repeat: initial initial;"><o:p></o:p></span></p>