<?php exit;?>2015-09-23 11:00:23&nbsp;<span style="line-height: 21px; font-family: 幼圆; color: rgb(96,96,107)">北京北琪医疗科技有限公司位于北京中关村科技园区内，是一家台资高新技术企业，由多位具有多年行业领导经验的专业人员与海外留学生于2005年共同建立。成立7年来，北琪公司秉持&ldquo;团结诚信，追求卓越&rdquo;的公司理念，专注疼痛治疗设备领域的研发、生产、销售、培训，为国内市场提供极具性能价格比的射频热凝器系列产品，和国内疼痛微创治疗临床学界建立了稳定和坚实的合作关系，得到许多专家的肯定和支持，成为国内射频疼痛治疗仪用户的首选产品，市场占有率领先。</span>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; 北京北琪医疗科技有限公司以市场需求为导向，注重研发，在射频疼痛治疗仪技术方面傲视同侪，拥有国内多项首创，许多第一：</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;第一支直径0.4毫米的疼痛射频电极（2007年）；</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<span style="font-family: 幼圆; font-size: 14px">第一支直径0.7毫米的射频套管针（2007年）；</span><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp;&nbsp;</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;国内首创的机外测试狗（2007年）；</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;国内首台带有脉冲射频的射频热凝器（2007年）；</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;国内首台带有电压刺激电流刺激双刺激模式的射频热凝器（2007年）；</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;首个热凝器信息管理系统（2007年）；</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;第一支适用于高温高压灭菌的疼痛射频电极（2009年）；</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-size: 14px"><span style="font-family: 幼圆">&nbsp; &nbsp; &nbsp;国内首台双极双测温射频热凝器（2012年）；</span></span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;</span><span style="font-family: 幼圆; font-size: 14px">首创全功能手控器（2012年）。</span>&nbsp;<font size="2">　　</font><span style="font-size: small">　　</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 。。。。。。</p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-size: 14px"><span style="font-family: 幼圆">&nbsp; &nbsp; &nbsp;北琪射频热凝器质量是北琪员工引以为豪的地方，长期以来秉持</span><span style="font-family: 幼圆">&ldquo;</span></span><span style="font-family: 幼圆"><span style="font-size: 14px">品质源自于对细节的雕琢，源自于对流程的执行，源自于员工内心的责任感&rdquo;的产品质量方针，</span><span style="font-size: 14px">对产品质量要求持之以恒的坚持，铸就了北琪产品的今天，全国各地的<span style="font-size: 16px"><span style="color: rgb(255,0,0)">用户</span></span>是我们见证。</span></span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;北京北琪医疗科技有限公司以客户为中心，除了向客户提供技术先进，质量优异的产品之外，还为客户提供多方位、多层次的服务：</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;装机服务，客户购买北琪热凝器后，服务人员上门提供机器使用操作培训，保证客户的操作使用无忧；</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;临床培训，临床使用的培训有多种方式和层次，可以专家上门手术指导，也可以到北琪公司临床培训合作医院参观学习，也可以安排客户到三甲医院<span style="font-size: 16px"><span style="color: rgb(255,0,0)">进修培训</span></span>；</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;专题学习班，北琪公司不仅是做产品的销售，更关注的是用户在购买北琪产品后能够会用，能够用好北琪产品，在基本的培训基础上，北琪公司常年在全国各地轮流开办射频技术学习班，聘请专家就射频技术应用的基本原理、临床技术最新进展、疼痛科建设等广大用户急切想知道、想提高的方面作进一步的指导和交流，希望北琪公司的努力，能够为中国疼痛治疗设备市场的规范、健康发展，为解决疼痛病人的痛楚贡献出北琪人绵薄之力。</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-family: 幼圆; font-size: 14px">&nbsp; &nbsp; &nbsp;产品维修，当设备出现故障时，除了可以联系我们的业务人员报修之外，亦可拨打北琪公司的电话400-0345-800（免长途话费），和售后服务人员联系沟通后，根据故障情况的不同，北琪公司可以提供周转机给客户，减少产品故障对医院使用的影响。</span></p>
<p style="line-height: 21px; text-indent: 0px; font-family: 宋体, Arial; color: rgb(96,96,107); font-size: 12px"><span style="font-size: 14px"><span style="font-family: 幼圆">&nbsp; &nbsp; &nbsp;北琪立志做中国一流的医疗科技公司，选择北琪是您正确的决定，北琪公司值得您信赖。</span></span></p>