<?php exit;?>2014-11-14 17:03:52<p><font color="#333333" face="宋体">&nbsp;CSN100A低频半导体激光综合治疗仪，利用世界先进的超低频数控电脉冲技术，结合尖端半导体生物技术，根据传统中医理论，通过穴位刺激，药物离子导入，促进局部微循环消炎杀菌，调节免疫功能，增强机体抗病能力。迅速缓减过敏性鼻炎，单纯性鼻炎引起的症状，是非介入、非药物治疗鼻炎咽炎及中耳炎的高科技现代化的电子绿色生物产品。 <br />
治疗原理：经典传统中医理论及高科技半导体生物技术双结合<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &mdash;&mdash;提升三腔机体免疫力，提升抗病能力。</font></p>
<p><font color="#333333" face="宋体">&nbsp;</font></p>
<p><font color="#333333" face="宋体">（一） 超低频数控糅合多种输出波形的电脉冲刺激鼻两侧迎香穴，药物离子导入经典疗法。</font></p>
<p><font color="#333333" face="宋体">&nbsp; 低频脉冲采用三角波和指数波及多种频率输出方式，实现模拟传统中医敲击，推拿，按摩功能。传统中医理论，迎香穴是有效治疗鼻炎的穴位，并被大量的医学实践证明，迎香穴位鼻孔两侧，鼻唇沟内，与鼻腔的神经、血管有密切的联系。针对迎香穴的治疗能抑制和降低毛细血管和细胞膜的通透性，减少炎症渗出，改善鼻通气，对鼻炎有很好的治疗效果。低频电刺激可加强肌肉活动，增加组织间的相对运动，可使轻度的粘连松解。同时当肌肉强烈收缩时，其中的静脉和淋巴管即被挤压排空，肌肉松驰时，静脉和淋巴管随之扩张和充盈，因此用电刺激肌肉产生有<br />
节律的收缩，可改善血液和淋巴循环，促进静脉的淋巴的回流。同时利用这两种波的高尖部分达到组织的兴奋阀，就可以兴奋正常的运动神经和肌肉。电脉冲具有使人体肌肉组织产生电阻性发热、促进神经肌肉电兴奋的作用，从而具有解痉镇痛、消炎、改善血液循环、提高机体免疫力等功能，通过低频的双向部分使电场组织中的离子产生来回移动，降低对组织的电解影响。</font></p>
<p>&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><img style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; border-top: 0px; border-right: 0px; padding-top: 0px" border="0" alt="" width="350" height="300" src="http://www.tecenet.com/file/upload/201411/14/15-21-34-24-30396.jpg" /></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><span style="padding-bottom: 0px; background-color: rgb(0,0,255); margin: 0px; padding-left: 0px; padding-right: 0px; color: rgb(255,153,204); font-size: 14pt; padding-top: 0px"><font style="background-color: #ffffff" color="#333333">（二）窄频半导体激光鼻腔照射，尖端生物技术和现代医学的结合</font></span></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><span style="padding-bottom: 0px; background-color: rgb(0,0,255); margin: 0px; padding-left: 0px; padding-right: 0px; color: rgb(255,153,204); font-size: 14pt; padding-top: 0px"><font style="background-color: #ffffff" color="#333333">&nbsp; 半导体激光部分采用现代生物光医学技术，以波长660nm半导体激光，通过光纤传导，直接照射作用于鼻腔的敏感区，引起血管扩张，流血加快，使鼻腔血系中，酶和蛋白分子构象发生改变而产生换能性生物效应。通过刺激鼻腔内交感神经和副交感神经，增强鼻粘膜血管收缩扩张弹性。并在直接杀灭鼻内腔表层病菌的同时，剥离血红细胞表面包裹层，使细胞带负电荷数量恢复正常；相互排斥力加大，把原来聚焦成团的红细胞分散开。从而促进鼻腔血系发育及携氧能力，增强鼻腔自身的杀菌免疫及再生机能，快速修复受损鼻黏膜，从根本上消除病症，最终达到治愈鼻炎的目的。红光使免疫细胞受体对花粉等刺激物的反应变慢；这种特定光波导致肥大细胞壁通透性减弱，这就意味着组胺的释放量减少；免疫细胞的结合作用受到局部影响，从而降低了对过敏因子的反应。</font></span></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><img style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; border-top: 0px; border-right: 0px; padding-top: 0px" border="0" alt="" width="400" height="250" src="http://www.tecenet.com/file/upload/201411/14/15-21-34-58-30396.jpg" /></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><span style="padding-bottom: 0px; background-color: rgb(0,0,255); margin: 0px; padding-left: 0px; padding-right: 0px; color: rgb(255,153,204); font-size: 14pt; padding-top: 0px"><font style="background-color: #ffffff" color="#333333">（三） 窄频半导体激光中耳照射</font></span></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><span style="padding-bottom: 0px; background-color: rgb(0,0,255); margin: 0px; padding-left: 0px; padding-right: 0px; color: rgb(255,153,204); font-size: 14pt; padding-top: 0px"><font style="background-color: #ffffff" color="#333333">&nbsp;&nbsp;&nbsp;&nbsp; 中耳炎多因鼻腔、咽喉感染，向咽鼓管蔓延，致病菌乘虚侵入中耳引发炎症。如急性中耳炎未能及时治疗，或病情过重就会发展为慢性中耳炎，迁延日久，会引发脑部感染等并发症，特别对于儿童的智力发育和生命健康都是极大威胁。持续发射660纳米的软激光，采用集束光波持续治疗可断脓，消除症状，物理疗法，没有药物副作用，可以放心地使用。</font></span></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><img style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; border-top: 0px; border-right: 0px; padding-top: 0px" border="0" alt="" width="350" height="300" src="http://www.tecenet.com/file/upload/201411/14/15-21-34-63-30396.jpg" /></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><span style="padding-bottom: 0px; background-color: rgb(0,0,255); margin: 0px; padding-left: 0px; padding-right: 0px; color: rgb(255,153,204); font-size: 14pt; padding-top: 0px"><font style="background-color: #ffffff" color="#333333">（四） 窄频半导体口腔照射治疗</font></span></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><span style="padding-bottom: 0px; background-color: rgb(0,0,255); margin: 0px; padding-left: 0px; padding-right: 0px; color: rgb(255,153,204); font-size: 14pt; padding-top: 0px"><font style="background-color: #ffffff" color="#333333">&nbsp;&nbsp;&nbsp;&nbsp; 半导体激光能改变神经纤维对 K+Na+离子的通透性；使神经末梢动作电位增加，同时刺激神经轴突的内非肽形成。从而起到镇痛作用，所以半导体激光治疗仪可改变血管通透性，降低炎症，使充血消肿减轻。同时可扩张血管，加速血流促进炎症减退。促进口腔代谢和组织修复，加速局部物质产生。抑制炎症，减轻疼痛。提高免疫功能，增强白细胞的吞噬作用。该产品经许多医院口腔科广泛应用，已确定对以下病症有明显的疗效：牙本质过敏、各种粘膜溃疡、牙龈炎、冠周炎、颞颌关节炎、腮腺炎、口腔溃疡等。此外，还可用于拔牙术后疼痛、咽炎、扁桃体炎等。</font></span></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><img style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; border-top: 0px; border-right: 0px; padding-top: 0px" border="0" alt="" width="300" height="400" src="http://www.tecenet.com/file/upload/201411/14/15-21-34-77-30396.jpg" /></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><span style="padding-bottom: 0px; background-color: rgb(0,0,255); margin: 0px; padding-left: 0px; padding-right: 0px; color: rgb(255,153,204); font-size: 14pt; padding-top: 0px"><strong style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">（五）半导体体外部理疗</strong></span></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">&nbsp;&nbsp;&nbsp;&nbsp; 生物体细胞中线粒体在半导体光照射后，过氧化氢酶活性增加，细胞的新陈代谢增强，使糖元含量增加，蛋白合成增加和三磷酸腺昔分解增加，从而加强细胞的新生，促进伤口和溃疡的愈合；同时也增加白血球的吞噬作用，提高机体的免疫功能：使病变组织产生重要的生物效应从而达到治愈的目的。</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">&nbsp;</p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px"><span style="padding-bottom: 0px; background-color: rgb(0,0,255); margin: 0px; padding-left: 0px; padding-right: 0px; color: rgb(255,153,204); font-size: 14pt; padding-top: 0px"><strong style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">仪器适应症：</strong></span></p>
<p style="padding-bottom: 0px; line-height: 20px; text-indent: 0px; margin: 0px; padding-left: 5px; padding-right: 0px; font-family: 宋体; color: rgb(51,51,51); padding-top: 0px">■过敏性鼻炎、急慢性鼻炎、鼻窦炎、药物性鼻炎<br />
■干燥性鼻炎等各种鼻炎患者 有鼻炎、鼻窦炎引起的鼻塞、<br />
打喷嚏、头晕、头痛、听力、记忆力下降、视力模糊、精神萎<br />
靡等症状人群。<br />
■口腔科：牙本质过敏、各种粘膜溃疡、牙龈炎、冠周炎、<br />
颞颌关节炎、腮腺炎、口腔溃疡等。此外，还可用于拔牙术<br />
后疼痛、咽炎、扁桃体炎等。<br />
■中耳炎患者：急慢性中耳炎，化脓及非化脓性中耳炎。<br />
■长期用药，仍久治不愈，并产生药物耐受性的患者<br />
■曾使用多种治疗方式，仍反复发作，已丧失治疗信心的患者</p>