<?php exit;?>2015-09-30 11:57:28<p style="">&nbsp;</p>
<blockquote style="margin-right: auto; margin-left: auto; padding: 12px 5px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; font-size: 15px; line-height: 24px; font-family: 微软雅黑; min-height: 1em; text-align: justify; box-sizing: border-box !important; word-wrap: break-word !important; background-image: -webkit-linear-gradient(left, rgb(219, 238, 243), rgb(255, 255, 250), rgb(219, 238, 243)); background-color: rgb(255, 255, 240);">
<h1 style="margin: 0px; padding: 0px; font-weight: normal; font-size: 16px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(73, 68, 41); font-family: Arial; line-height: 25px;"><blockquote style="padding: 10px 15px; max-width: 100%; border-width: 6px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-color: rgb(242, 166, 2); color: rgb(68, 68, 68); line-height: 23.99px; font-family: 微软雅黑; font-size: 13.33px; border-top-left-radius: 50px; border-bottom-right-radius: 50px; box-shadow: rgb(165, 165, 165) 5px 5px 2px; box-sizing: border-box !important; word-wrap: break-word !important;">
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="http://www.tecenet.com/file/upload/weixin/image/cj2UFHy2yQBia26PjIAWREEXAEJD3gzPtzMPfdLxNjmr0GOnDbxMdu6AO4e8cwhosMjWNlfDVxxnK5sPzibOeLSA.jpeg#" width="280" widthd="auto" data-ratio="0.5982142857142857" data-w="448" data-s="300,640" data-type="jpeg" style="margin: 0px; padding: 0px; text-align: justify; color: rgb(79, 97, 40); font-size: 18px; line-height: 23px; box-sizing: border-box ! important; word-wrap: break-word ! important; width: auto ! important; visibility: visible ! important; height: auto ! important;" height="167" alt="" /></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(79, 97, 40); font-size: 16px;">这年头，<br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">有纹身的都怕热，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">用苹果的都没兜，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">带手表的爱拍腿，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">镶金牙的爱咧嘴。</span></p>
</blockquote>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<blockquote style="padding: 10px 15px; max-width: 100%; border-width: 6px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-color: rgb(242, 166, 2); color: rgb(68, 68, 68); line-height: 23.99px; font-family: 微软雅黑; font-size: 13.33px; border-top-left-radius: 50px; border-bottom-right-radius: 50px; box-shadow: rgb(165, 165, 165) 5px 5px 2px; box-sizing: border-box !important; word-wrap: break-word !important;">
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="http://www.tecenet.com/file/upload/weixin/image/logX43iaMBeL49jPnkhtILNVNZNicdSIIpknDvtsaoE3T2GQB3ZNibIOQazocJFeDFTiagKuHN0ibZ4bwk75EL4GYibQ.jpeg#" width="320" widthd="auto" data-s="300,640" data-ratio="0.7166123778501629" data-w="307" style="margin: 0px; padding: 0px; font-size: 13.33px; line-height: 23.99px; box-sizing: border-box ! important; word-wrap: break-word ! important; width: auto ! important; visibility: visible ! important; height: auto ! important;" alt="" /></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">现如今，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">没结婚的像结婚的一样同居，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">结婚的像没结婚的一样分居。</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">动物像人一样穿衣服，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">人像动物一样露着肉。</span></p>
</blockquote>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<blockquote style="padding: 10px 15px; max-width: 100%; border-width: 6px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-color: rgb(242, 166, 2); color: rgb(68, 68, 68); line-height: 23.99px; font-family: 微软雅黑; font-size: 13.33px; border-top-left-radius: 50px; border-bottom-right-radius: 50px; box-shadow: rgb(165, 165, 165) 5px 5px 2px; box-sizing: border-box !important; word-wrap: break-word !important;">
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); line-height: 2em; overflow: hidden; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="http://www.tecenet.com/file/upload/weixin/image/logX43iaMBeL49jPnkhtILNVNZNicdSIIpAziaXSc9iaBt3HoEfib7EtQzV2yL1zk9Kxv6LDPSoa9xCO1kkibwrDAx0g.jpeg#" width="320" widthd="auto" data-s="300,640" data-ratio="0.6586826347305389" data-w="334" style="margin: 0px; padding: 0px; color: rgb(68, 68, 68); font-size: 13.33px; line-height: 23.99px; box-sizing: border-box ! important; word-wrap: break-word ! important; width: auto ! important; visibility: visible ! important; height: auto ! important;" alt="" /></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">小孩子像大人一样成熟，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">大人像小孩子一样幼稚。</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">女人像男人一样爷们，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">男人像女人一样娘们。</span></p>
</blockquote>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<blockquote style="padding: 10px 15px; max-width: 100%; border-width: 6px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-color: rgb(242, 166, 2); color: rgb(68, 68, 68); line-height: 23.99px; font-family: 微软雅黑; font-size: 13.33px; border-top-left-radius: 50px; border-bottom-right-radius: 50px; box-shadow: rgb(165, 165, 165) 5px 5px 2px; box-sizing: border-box !important; word-wrap: break-word !important;">
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="http://www.tecenet.com/file/upload/weixin/image/logX43iaMBeL49jPnkhtILNVNZNicdSIIp8QHfYL1X4x4lbYKPlfYGAN4t1XVT4YSuTm2uPUgHIduibN5rupu5vog.jpeg#" width="320" widthd="auto" data-s="300,640" data-ratio="0.7028753993610224" data-w="313" style="margin: 0px; padding: 0px; box-sizing: border-box ! important; word-wrap: break-word ! important; width: auto ! important; visibility: visible ! important; height: auto ! important;" alt="" /></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">没钱的像有钱的一样装富，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">有钱的像没钱的一样装穷。</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">情人像夫人一样四处招摇，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">夫人像情人一样深入简出。</span></p>
</blockquote>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<blockquote style="padding: 10px 15px; max-width: 100%; border-width: 6px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-color: rgb(242, 166, 2); color: rgb(68, 68, 68); line-height: 23.99px; font-family: 微软雅黑; font-size: 13.33px; border-top-left-radius: 50px; border-bottom-right-radius: 50px; box-shadow: rgb(165, 165, 165) 5px 5px 2px; box-sizing: border-box !important; word-wrap: break-word !important;">
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="http://www.tecenet.com/file/upload/weixin/image/logX43iaMBeL49jPnkhtILNVNZNicdSIIpaOD9jc0vlVd8fDLezxXXQvQBBwScUiaGxSnN7YJkicojUMtCYbz9oeqw.jpeg#" width="320" widthd="auto" data-s="300,640" data-ratio="0.6606606606606606" data-w="333" style="margin: 0px; padding: 0px; font-size: 13.33px; line-height: 23.99px; box-sizing: border-box ! important; word-wrap: break-word ! important; width: auto ! important; visibility: visible ! important; height: auto ! important;" alt="" /></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">网上说：</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">现在存折里不到百万的，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">不叫存款，叫余额。</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">审视了一下自己，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">原来，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">自己的那点只能叫手续费，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">有时候连手续费都不足。</span></p>
</blockquote>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<blockquote style="padding: 10px 15px; max-width: 100%; border-width: 6px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-color: rgb(242, 166, 2); color: rgb(68, 68, 68); line-height: 23.99px; font-family: 微软雅黑; font-size: 13.33px; border-top-left-radius: 50px; border-bottom-right-radius: 50px; box-shadow: rgb(165, 165, 165) 5px 5px 2px; box-sizing: border-box !important; word-wrap: break-word !important;">
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); line-height: 2em; overflow: hidden; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="http://www.tecenet.com/file/upload/weixin/image/logX43iaMBeL49jPnkhtILNVNZNicdSIIpoaFs95GfJH4moyO4RiaARZRLc7UczzBfV9cgKpQUuJUvf7UFYlu5YRA.jpeg#" width="320" widthd="auto" data-s="300,640" data-ratio="0.6657142857142857" data-w="350" style="margin: 0px; padding: 0px; box-sizing: border-box ! important; word-wrap: break-word ! important; width: auto ! important; visibility: visible ! important; height: auto ! important;" alt="" /></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">慢慢明白了，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">戴三百块的表和三百万的表，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">时间是一样的；</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">喝三十块的酒和三千块的酒，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">呕吐是一样的；</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">住三十平米的房和三百平米的房，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">孤独是一样的。</span></p>
</blockquote>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<blockquote style="padding: 10px 15px; max-width: 100%; border-width: 6px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-color: rgb(242, 166, 2); color: rgb(68, 68, 68); line-height: 23.99px; font-family: 微软雅黑; font-size: 13.33px; border-top-left-radius: 50px; border-bottom-right-radius: 50px; box-shadow: rgb(165, 165, 165) 5px 5px 2px; box-sizing: border-box !important; word-wrap: break-word !important;">
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="http://www.tecenet.com/file/upload/weixin/image/logX43iaMBeL49jPnkhtILNVNZNicdSIIpt1AzL2TtrjgPQggbCRlVFNV5pBPtjeW23ljm0fJibr42GVMxiaAreIWg.jpeg#" width="320" widthd="auto" data-s="300,640" data-ratio="0.668693009118541" data-w="329" style="margin: 0px; padding: 0px; font-size: 13.33px; line-height: 23.99px; white-space: normal; box-sizing: border-box ! important; word-wrap: break-word ! important; width: auto ! important; visibility: visible ! important; height: auto ! important;" alt="" /></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">总有一天你会知道，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">你内心真正的快乐，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">是物质世界永远给予不了的&hellip;</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">抽十块的烟和抽100块的烟都会得肺癌，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">坐头等舱和坐经济舱失联了一样都回不来...</span></p>
</blockquote>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<blockquote style="padding: 10px 15px; max-width: 100%; border-width: 6px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-color: rgb(242, 166, 2); color: rgb(68, 68, 68); line-height: 23.99px; font-family: 微软雅黑; font-size: 13.33px; border-top-left-radius: 50px; border-bottom-right-radius: 50px; box-shadow: rgb(165, 165, 165) 5px 5px 2px; box-sizing: border-box !important; word-wrap: break-word !important;">
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="http://www.tecenet.com/file/upload/weixin/image/Tp76VHR3AFmsudPILIzHX5haEfIo8j9iaAWLjBr1tjdPqkMvyiaibu1PbY10WXiaXkGY2k4KT0nvd7C9cHsxZtEuyA.jpeg#" width="320" widthd="389px" data-s="300,640" data-type="jpeg" data-ratio="0.6863753213367609" data-w="389" style="margin: 0px; padding: 0px; font-size: 13.33px; line-height: 23.99px; box-sizing: border-box ! important; word-wrap: break-word ! important; width: 389px ! important; visibility: visible ! important; height: auto ! important;" alt="" /></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(79, 97, 40); font-size: 16px; line-height: 23.99px;">所以，<br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">想明白了，</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">知足常乐...</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">和谁在一起活着才是最重要的！</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">谁能陪着你才是最难得的！</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(79, 97, 40); font-size: 16px; line-height: 23.99px;">生活已不易！<br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
</span></p>
<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; min-height: 1em; white-space: pre-wrap; text-align: center; line-height: 2em; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 16px;">且行且珍惜！ </span></p>
</blockquote></h1>
</blockquote>
<p>&nbsp;&nbsp;</p>
<blockquote class="brcolor" style="padding: 10px; border-top-width: 3px; border-right-width: 3px; border-bottom-width: 3px; border-style: dotted; border-color: rgb(80, 130, 189); font-size: 17.1428565979004px; white-space: normal; border-radius: 5px !important;">
<h3 style="color: rgb(89, 89, 89); font-size: 14px; margin: 0px;"><span style="color: rgb(255, 255, 255); padding: 2px 5px; font-size: 16px; margin-right: 15px; border-radius: 5px !important; background-color: rgb(80, 130, 189);">天成医疗-电子商务部</span></h3>
<p><span style="font-size: 16px;">一家专门为医疗机构、生产厂家和经销商提供专业技术和产品服务的电子商务交易平台，关注我们，千千万万个商业机会等着你。</span></p>
<p><span style="font-size: 16px;">服务热线：<span style="font-size: 16px; margin: 0px; padding: 0px; max-width: 100%; color: rgb(0, 176, 240); box-sizing: border-box !important; word-wrap: break-word !important;"><br />
业务联系 18588655941 张先生</span></span></p>
<p>&nbsp;</p>
<p><span style="font-size: 16px;">更多服务内容请登录<br />
天成医疗网：<strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="font-size: 16px; margin: 0px; padding: 0px; max-width: 100%; color: rgb(0, 176, 240); box-sizing: border-box !important; word-wrap: break-word !important;">www.tecenet.com</span></strong></span></p>
微信公众号：<strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 16px; color: rgb(0, 176, 240); box-sizing: border-box !important; word-wrap: break-word !important;">tianchengyiliao</span></strong></blockquote>