<?php exit;?>2015-07-23 15:04:00<br />
<p style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><strong><font size="5">JAZ&mdash;1型</font></strong></span></span></p>
<p style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><strong><font size="5">康恩斯电位治疗仪制造工艺</font></strong></span></span></p>
<ol style="background-image: none; text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); list-style-type: none; text-indent: 0px; margin: 0px; padding-left: 25px; width: auto; background-attachment: scroll; letter-spacing: normal; padding-right: 0px; display: inline-block; font: medium/20px 'Times New Roman'; white-space: normal; background-position: 0% 0%; float: none; height: auto; color: rgb(0,0,0); list-style-image: none; word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px">
    <li style="list-style: decimal none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">采用原装进口的ISD4003&mdash;04MPY和ATMEGA64A新型芯片。</span></span></li>
    <li style="list-style: decimal none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">进口原装电子原件，安全，稳定。</span></span></li>
    <li style="list-style: decimal none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">著名电台播音员中英文录音，语音播报清晰悦耳。</span></span></span></span></li>
    <li style="list-style: decimal none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">机器外壳工艺是目前国内同类产品中级别最高的。</span></span></span></span></span></span></li>
    <li style="list-style: decimal none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">采用美国进口的Acrylonitrile Butadiene Styrene（ABS）原材料制作，具有综合性能好,冲击强度较高,稳定性能良好.有高抗冲、高耐热、阻燃、增强、透明等级别，【外壳成型收缩率仅:0.4-0.7%，模具温度：25-70℃（模具温度将影响塑件光洁度，温度较低则导致光洁度较低），融化温度：130-160℃或更高）成型温度：200-240℃，注射压力：1000bar】。</span></span></span></span></span></span></span></span></li>
    <li style="list-style: decimal none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">自动化机械装配，稳定，耐用。</span></span></span></span></span></span></span></span></span></span></li>
    <li style="list-style: decimal none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">采用滴水消失防伪技术。</span></span></span></span></span></span></span></span></span></span></li>
</ol>
<p style="text-align: center; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px"><img style="padding-bottom: 0px; border-right-width: 0px; margin: 0px; padding-left: 0px; width: 625px; padding-right: 0px; border-top-width: 0px; border-bottom-width: 0px; height: 2752px; vertical-align: middle; border-left-width: 0px; padding-top: 0px" alt="" src="http://www.tecenet.com/file/upload/201507/23/14-59-36-50-33050.jpg" /></p>
<p style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><font size="5"><strong>保养维修</strong></font></span></span></p>
<p style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px">&nbsp;</p>
<ul style="background-image: none; text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); list-style-type: none; text-indent: 0px; margin: 0px; padding-left: 25px; width: auto; background-attachment: scroll; letter-spacing: normal; padding-right: 0px; display: inline-block; font: medium/20px 'Times New Roman'; white-space: normal; background-position: 0% 0%; float: none; height: auto; color: rgb(0,0,0); clear: both; list-style-image: none; word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px">
    <li style="list-style: disc none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px 1px 0px 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">电位治疗仪是精密仪器，切勿摇晃碰撞，不要在高温、潮湿、多灰尘有烟的地方使用或存放，也不要在阳光直射的地方使用和存放，应选空气干燥，环境优良无烟碱、无硫磺等腐蚀性物质的地方使用或存放。</span></span></li>
    <li style="list-style: disc none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px 1px 0px 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">请保持机器和导波垫的干燥清洁，主机上禁止放水杯、花瓶等物品。主机机体和导波坐垫要防止潮湿及异物进入。</span></span></li>
    <li style="list-style: disc none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px 1px 0px 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">使用中如发生故障，应立即关闭电源，联系经销商或厂家进行维修。</span></span></li>
    <li style="list-style: disc none outside; background-image: none; text-align: left; padding-bottom: 0px; line-height: normal; background-color: transparent; margin: 0px 1px 0px 0px; padding-left: 0px; width: auto; background-attachment: scroll; padding-right: 0px; background-position: 0% 0%; float: none; height: auto; padding-top: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">两年品质保障，终身维修。如人为损坏，不属于免费保修范围。</span></span></li>
</ul>
<p style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px">&nbsp;</p>
<p style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><strong>体积:490&times;330&times;270mm</strong></span></span></p>
<p style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><strong>重量：10kg</strong></span></span></p>
<p style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px">&nbsp;</p>
<p style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><strong>附件：</strong></span></span></p>
<p style="text-align: center; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; letter-spacing: normal; padding-right: 0px; font: medium 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px">&nbsp;</p>
<table style="text-align: left; padding-bottom: 0px; text-transform: none; background-color: rgb(255,255,255); text-indent: 0px; margin: 0px; padding-left: 0px; width: 522px; letter-spacing: normal; padding-right: 0px; border-collapse: collapse; font: medium/20px 'Times New Roman'; white-space: normal; color: rgb(0,0,0); word-spacing: 0px; padding-top: 0px; -webkit-text-stroke-width: 0px" border="1" cellspacing="0" bordercolor="#666666" cellpadding="0">
    <tbody>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><strong>序号</strong></span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><strong>名称</strong></span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><strong>数量</strong></span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><strong>单位</strong></span></span></td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">1</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">导波座垫</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">1</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">张</span></span></td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">2</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">电源线</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">1</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">条</span></span></td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">3</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">保险丝</span></span></span></span></span></span></span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">2</span></span></span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">个</span></span></span></span></td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">4</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">局部效应器</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">1</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">件</span></span></td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">5</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">说明书</span></span></span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">1</span></span></span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">本</span></span></td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">6</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">质量保修单</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">1</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">份</span></span></td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">7</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">合格证</span></span></span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">1</span></span></td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center"><span style="font-size: 10pt"><span style="font-family: arial, helvetica, sans-serif">张</span></span></td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
        </tr>
        <tr style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
            <td style="padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" valign="middle" align="center">&nbsp;</td>
        </tr>
    </tbody>
</table>