<?php exit;?>2015-07-14 16:10:55&nbsp;
<div class="rich_media_thumb_wrp" id="media" style="margin: 0px; padding: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 16px; line-height: 25.6000003814697px;"><img src="http://www.taoseoer.com:8099/updat&#101;/yemian/2_files/1.jpg" name="js_cover" width="600" height="333" class="rich_media_thumb" id="js_cover" data-s="300,640" style="margin: 0px 0px 6px; padding: 0px; width: 670px; height: auto !important;" alt="" /></div>
<div class="rich_media_content" id="js_content" style="margin: 0px; padding: 0px; overflow: hidden; color: rgb(62, 62, 62); position: relative; min-height: 350px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', Arial, sans-serif; font-size: 16px; line-height: 25.6000003814697px;">
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); font-size: 20px; box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">7天加满5000微信好友</strong></span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); font-size: 20px; box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">全部精准粉丝，主动来加你好友</strong></span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); font-size: 20px; box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">你今天可以免费获得本方法</strong></span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; box-sizing: border-box !important; word-wrap: break-word !important;">这套绝招是《大神微信营销团队》用了3个多月的时间，7人团队、花费15000元测试资金，所得出的一套目前互联网上</span><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; box-sizing: border-box !important; word-wrap: break-word !important; background-color: rgb(255, 255, 0);">绝无仅有的一套</span><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; box-sizing: border-box !important; word-wrap: break-word !important;">《7天轻松吸粉破5000人》</span><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; box-sizing: border-box !important; word-wrap: break-word !important; background-color: rgb(255, 255, 0);">微信吸粉绝招</span><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; box-sizing: border-box !important; word-wrap: break-word !important;">。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; box-sizing: border-box !important; word-wrap: break-word !important;"> </span></p>
<p align="center" style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;"><span class="STYLE6" style="margin: 0px; padding: 0px; max-width: 100%; font-size: 20px; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">零投入便可倍增粉丝 </strong> </span></p>
<p align="center" style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;"><span class="STYLE6" style="margin: 0px; padding: 0px; max-width: 100%; font-size: 20px; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">【无需任何软 不投入1分钱】 </strong> </span></p>
<p align="center" style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;"><span class="STYLE6" style="margin: 0px; padding: 0px; max-width: 100%; font-size: 20px; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">并且...全是精准活粉 </strong> </span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; box-sizing: border-box !important; word-wrap: break-word !important; background-color: rgb(255, 255, 0);">请看了下面这个视频！！！</span></p>
<p>&nbsp;</p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 20px; box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;">绝对震撼！绝对刺激你的眼球！</span></strong></span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 20px; box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;">刺激你的双耳！</span></strong></span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; box-sizing: border-box !important; word-wrap: break-word !important;">震撼吸粉效果录像视频： </span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 18px; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;">（有声音请把声音放大）</span></p>
<p>&nbsp;</p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 20px; box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;">是不是很震撼 </span></strong></span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-size: 20px; box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;">是不是特别想知道 我是如何做到的？</span></strong></span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important;">你只需要 长按图片 <strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">扫描下面二维码</strong> 加我为好友 ！！就能<span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; background-color: rgb(255, 255, 0);"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">免费领取</strong></span>了！</p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;">&nbsp;<img src="http://www.tecenet.com/file/upload/201507/14/16-09-12-28-1.jpg" style="line-height: 25.6000003814697px;" alt="" /></p>
<p align="center" class="STYLE3" style="margin: 0px; padding: 0px; max-width: 100%; font-size: 24px; font-weight: bold; clear: both; min-height: 1em; white-space: pre-wrap; text-indent: 0px; box-sizing: border-box !important; word-wrap: break-word !important;">长按并识别二维码 添加好友</p>
<p align="center" class="STYLE2" style="margin: 0px; padding: 0px; max-width: 100%; font-size: 24px; color: rgb(255, 0, 0); font-weight: bold; clear: both; min-height: 1em; white-space: pre-wrap; text-indent: 0px; box-sizing: border-box !important; word-wrap: break-word !important;">免费领取！</p>
</div>