<?php exit;?>2015-09-01 16:07:44<div style="text-align: center">&nbsp;<img style="background-image: none; border-bottom: medium none; text-align: center; border-left: medium none; padding-bottom: 0px; line-height: 18px; text-indent: 2em; margin: 0px; padding-left: 0px; width: 500px; padding-right: 0px; font-family: 宋体, arial, sans-serif; height: 359px; color: rgb(102,102,102); font-size: 12px; vertical-align: middle; border-top: medium none; border-right: medium none; padding-top: 0px" title="1440205095763536.png" border="0" alt="1440205095763536.png" width="500" height="359" src="http://www.tecenet.com/file/upload/201508/25/11-42-14-56-30816.png" /></div>
<p style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px">&nbsp;</p>
<p style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px"><span style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-size: 14px; border-top: 0px; border-right: 0px; padding-top: 0px">&nbsp; &nbsp; 近日，李来柱上将来<font color="#136ec2"><strong>惠斯安普</strong></font>进行考察。李老将军从北京军区司令员岗位退下来以后，坚持参加社会活动，接受新的发展信息。此次来军政采购定点企业参观，也是李老的一次特别安排。</span></p>
<p style="border-bottom: 0px; text-align: center; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px"><img style="background-image: none; border-bottom: medium none; border-left: medium none; padding-bottom: 0px; margin: 0px; padding-left: 0px; width: 500px; padding-right: 0px; height: 560px; vertical-align: middle; border-top: medium none; border-right: medium none; padding-top: 0px" title="1440205127381959.png" border="0" alt="1440205127381959.png" width="500" height="560" src="http://www.tecenet.com/file/upload/201508/25/11-42-14-86-30816.png" /></p>
<p style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px">&nbsp;</p>
<p style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px"><span style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-size: 14px; border-top: 0px; border-right: 0px; padding-top: 0px">&nbsp;&nbsp;我是见山高兴，见水高兴，见大好形势高兴、见到人更高兴&mdash;&mdash;李来柱将军如是说。</span></p>
<p style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px">&nbsp;</p>
<p style="border-bottom: 0px; text-align: center; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px"><img style="background-image: none; border-bottom: medium none; border-left: medium none; padding-bottom: 0px; margin: 0px; padding-left: 0px; width: 500px; padding-right: 0px; height: 327px; vertical-align: middle; border-top: medium none; border-right: medium none; padding-top: 0px" title="1440205164830436.png" border="0" alt="1440205164830436.png" width="500" height="327" src="http://www.tecenet.com/file/upload/201508/25/11-42-14-47-30816.png" /></p>
<p style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px">&nbsp;</p>
<p style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px"><span style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-size: 14px; border-top: 0px; border-right: 0px; padding-top: 0px">&nbsp; &nbsp; 不吸烟，不喝酒，不乱花一分钱，是李来柱上将简朴生活的写照。李老每天以走路当上班，并且持之以恒，为我们从事健康管理的人做出了榜样。</span></p>
<p style="border-bottom: 0px; text-align: center; border-left: 0px; padding-bottom: 0px; line-height: 18px; text-indent: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-family: 宋体, arial, sans-serif; color: rgb(102,102,102); font-size: 12px; border-top: 0px; border-right: 0px; padding-top: 0px"><span style="border-bottom: 0px; border-left: 0px; padding-bottom: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; font-size: 14px; border-top: 0px; border-right: 0px; padding-top: 0px"><strong>&nbsp; &nbsp; 惠斯安普咨询热线：0335-8539894<br />
</strong>&nbsp;&nbsp;<br />
<br type="_moz" />
</span></p>