<?php exit;?>2015-04-27 12:22:44&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<b style="text-indent: 21pt; font-size: 14px;">广东仁修堂医药集团有限公司</b><span style="text-indent: 21pt; font-size: 14px;">，是由肇庆仁修堂医药有限公司、四会金葵花药业有限公司、广州业诚生物科技有限公司、岳阳今华医疗器械有限公司四家大健康产业企业，强强联手创立于</span><span lang="EN-US" style="text-indent: 21pt; font-size: 14px; font-family: Verdana, sans-serif;">2013</span><span style="text-indent: 21pt; font-size: 14px;">年</span><span lang="EN-US" style="text-indent: 21pt; font-size: 14px; font-family: Verdana, sans-serif;">10</span><span style="text-indent: 21pt; font-size: 14px;">月</span><span lang="EN-US" style="text-indent: 21pt; font-size: 14px; font-family: Verdana, sans-serif;">16</span><span style="text-indent: 21pt; font-size: 14px;">日，是</span><b style="text-indent: 21pt; font-size: 14px;">中山大学达安基因股份有限公司</b><span style="text-indent: 21pt; font-size: 14px;">（达安基因：</span><span lang="EN-US" style="text-indent: 21pt; font-size: 14px; font-family: Verdana, sans-serif;">002030</span><span style="text-indent: 21pt; font-size: 14px;">）的成员企业。</span>
<p style="text-indent:21.0pt">仁修堂医药集团的股东，均在大健康产业各链条中拥有丰富的从业经验，同时也一直致力于民族的健康事业发展。他们为了更好的创造和传递健康生活，本着资源互享、携手共进的合作理念，以&ldquo;分享成长，价值共赢&rdquo;作为企业核心价值观，围绕着&ldquo;大健康&rdquo;这个朝阳产业进行优化整合，创立了仁修堂这一立足全方位布局和运营的综合性大健康医药集团。<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<p style="text-indent:21.0pt">目前，仁俢堂医药集团主营业务主要包括大健康产品的<span lang="EN-US" style="font-family: Verdana, sans-serif;">OEM</span>代工生产、&ldquo;葵花<sup><span lang="EN-US" style="font-family: Verdana, sans-serif;">&reg;</span></sup>&rdquo;自主品牌的打造运营和医药零售终端（含电商）运营三大板块。集团公司拥有广州、岳阳、肇庆等多处生产基地和家喻户晓的&ldquo;葵花<sup><span lang="EN-US" style="font-family: Verdana, sans-serif;">&reg;</span></sup>&rdquo;品牌，同时是国药、哈药、广药、三九等多家医药巨头的长期合作伙伴，旗下七家公司构建了从研发生产（医疗器械、保健食品及食品、特妆、婴童及日化、卫生用品）到品牌运营（葵花<sup><span lang="EN-US" style="font-family: Verdana, sans-serif;">&reg;</span></sup>）及渠道运营（线上及线下）的完整大健康产销研一体产业体系，集团业务既符合国家产业政策也贴合市场需求，拥有广阔的发展前景。<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<p style="text-indent:21.0pt">集团旗下七大投资<span lang="EN-US" style="font-family: Verdana, sans-serif;">/</span>控股公司包括：<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<p style="text-indent:21.0pt">一、岳阳今华医疗器械有限公司（医疗器械生产）<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<p style="text-indent:21.0pt">二、肇庆仁修堂医药有限公司（食品及保健食品生产）<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<p style="text-indent:21.0pt">三、肇庆苗和堂医药有限公司（特妆、婴童及日化生产）<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<p style="text-indent:21.0pt">四、广州市伊亮日用品有限公司（牙膏、漱口水生产）<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<p style="text-indent:21.0pt">五、四会金葵花药业有限公司（自主品牌&ldquo;葵花<sup><span lang="EN-US" style="font-family: Verdana, sans-serif;">&reg;</span></sup>&rdquo;系列大健康产品的运营）<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<p style="text-indent:21.0pt">六、广州业诚生物科技有限公司（各工厂的<span lang="EN-US" style="font-family: Verdana, sans-serif;">OEM</span>接单公司）<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<p style="text-indent:21.0pt">七、清远市海马王药业有限公司（实体药店及网上药店的运营）<span lang="EN-US" style="font-family: Verdana, sans-serif;"><o:p></o:p></span></p>
<span style="font-size: 10.5pt; font-family: 宋体;">集团公司秉承真诚相邀和真心合作的信念，致力为客户提供优质的产品、良好的售后服务，并不断改进完善存在的不足，携手与各方有志于大健康产业的人士共同努力，为实现我国&ldquo;健康大国&rdquo;之梦而作出应有的贡献！</span>