<?php exit;?>2014-10-09 16:44:23<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="font-family: '宋体'; font-size: 10.5pt; mso-spacerun: 'yes'">&nbsp;</span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: bold; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">NT-proBNP<font face="宋体">检测试剂盒的临床应用：</font></span><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">&nbsp;</span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt; mso-list: l0 level1 lfo1" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-shading: rgb(250,250,250)"><span style="mso-list: Ignore">1.</span></span><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">早期发现心衰病人；&nbsp;</span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">2.<font face="宋体">心衰的诊断和危险分层；&nbsp;</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">3.<font face="宋体">区分心衰和其他原因引起的呼吸困难；&nbsp;</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">4.<font face="宋体">心衰治疗监测和预后评估；&nbsp;</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">5.<font face="宋体">非心源性心衰病人的筛选和诊断；&nbsp;</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">6.<font face="宋体">辅助</font><font face="Arial">ACS</font><font face="宋体">危险分层；</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">&nbsp;</span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: bold; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">cTnI<font face="宋体">的临床应用：&nbsp;</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt; mso-list: l1 level1 lfo2" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-shading: rgb(250,250,250)"><span style="mso-list: Ignore">1.</span></span><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">胸痛原因鉴别；&nbsp;</span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt; mso-list: l1 level1 lfo2" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-shading: rgb(250,250,250)"><span style="mso-list: Ignore">2.</span></span><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">ACS<font face="宋体">诊断和风险分层的基石；&nbsp;</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt; mso-list: l1 level1 lfo2" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-shading: rgb(250,250,250)"><span style="mso-list: Ignore">3.</span></span><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">ACS<font face="宋体">预后评估的最佳标志物；&nbsp;</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt; mso-list: l1 level1 lfo2" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-shading: rgb(250,250,250)"><span style="mso-list: Ignore">4.</span></span><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">急性心肌梗死的<font face="Arial">&ldquo;</font><font face="宋体">金标准</font><font face="Arial">&rdquo;</font><font face="宋体">；&nbsp;</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0"><span style="color: #000000"><span style="text-transform: none; font-style: normal; letter-spacing: 0pt; font-family: 'Arial'; background: rgb(250,250,250); font-size: 10.5pt; font-weight: normal; mso-spacerun: 'yes'; mso-shading: rgb(250,250,250)">5.<font face="宋体">检测心肌损伤的首选标志物，心肌特异性最高；<br />
<br />
</font></span></span></p>
<p style="margin-top: 0pt; margin-bottom: 0pt" class="p0">&nbsp;</p>